### ISSUE TITLE
Droid 4 - Hardware key not working [Enter]

### ISSUE THREAD

**Issue by eschwelgin** [maemo-leste/bugtracker#263] opened 2019-11-15 18:18 UTC
Issue has been present since first boot. My current workaround is enabling the virtual keyboard and pressing [hardware enter] and then [virtual enter] to send the keystroke. I've disabled and re-enabled the virtual keyboard several times, and without virtual keyboard the button is non-responsive. 

Seems to reproduce regardless of application, so far I've tested it in both x-terminal and netsurf. 

I don't see any mention of it in bugtracker or msg135137.html, so I'm thinking it's local to my install. 

Mind giving me some direction as to what to check next? 

Thanks

**Comment by MerlijnWajer** [comment] 2019-11-16 00:05
Does shift+enter or control+enter work?

**Comment by MerlijnWajer** [comment] 2019-12-12 03:20
To be clear, I think this is a bug in osso-xterm, not on the actual input level.

**Comment by dderby** [comment] 2019-12-12 04:27
I wonder if this relates to the age-old Fremantle bug where they mapped the hardware key to KP_ENTER.  This should be fixed in mainline Linux with the keymap found in the N900 dts.  Maybe there are some Maemo programs that expect to receive the keypad enter key and are not responsive to the main keyboard enter key, although I don't recall ever seeing this problem in osso-xterm under Leste.

**Comment by MerlijnWajer** [comment] 2019-12-12 05:10
I definitely see it in the virtual machine, on the N900 and on the Droid 4.

**Comment by eschwelgin** [comment] 2019-12-18 22:01
Sorry for not updating sooner, my device is having a battery issue. I was able to verify that shift + enter is working

**Comment by SimonIremonger** [comment] 2019-12-21 09:51
Yes, this is highly-likely related!  Somewhere I have some notes on things found-out.  From memory:-

I believe this 'hardware key' messes relates to N800/810 and is in the special gtk or X11 or libosso or wherever it is...    there are HARDKEY defines or that sort of thing.  Apparently the N810 direction-pad had middle-key mapped to enter, and a workaround in keyboard-map (they described as 'broken UI spec') was to use KP_Enter.

So far as leste goes, it would be highly desirable to get rid of that cruft in the gtk/X/wherever it is so that the 'normal' "Return" key is NOT nobbled any more, and osso-xterm similarly so it accepts normal Return.  I attempted to patch this out before, likely in gtk, and attempted to find issue within osso-xterm, but was not successful.  I did, however, get "normal" xterm working with Return key.

Once that 'now unhelpful Return nobbling logic' is removed [e.g. set to respond to F20 or some other nonexistant key!], the enhanced keymap  [ https://ec2.sheer.us/~enyc/n900-kbd/ ]  can be installed for N900, with Return rather than KP_Enter used...  and this mess with osso-xterm won't affect other devices either.

**Comment by dderby** [comment] 2019-12-22 16:16
I believe this may be the culprit:
https://salsa.debian.org/installer-team/console-setup/blob/master/Keyboard/ckb/symbols/nokia_vndr/rx-51#L426

**Comment by dderby** [comment] 2019-12-22 16:46
Actually maybe not, I forgot that this issue is for the Droid 4.  That keyboard map only affects the N900.

**Comment by SimonIremonger** [comment] 2020-01-08 10:39
eschwelgin  --
> I was able to verify that shift + enter is working
Can you confirm that even though, osso-xterm  does not work with 'normal enter key',  launch "xterm"  (possibly you may need to install xterm first),  the resulting "xterm"  DOES work with normal enter key?
If so, I may then have another look into code and try to point to source of this annoyance, might have been hildon-input-method or similar! =).

**Comment by eschwelgin** [comment] 2020-01-10 22:01
SimonIremonger -

Unfortunately my device is still having issues. Thought it was the battery not holding a charge but even on the charger it boots to the partition select and then stops with a little haptic feedback when maemo leste is selected. I may have caused this by letting the battery die while it was booted up

Wish I could do better for you

**Comment by MerlijnWajer** [comment] 2020-01-11 10:41
Working on testing my droid4 image. Will upload one really soon. Let's work from that one and see what we can improve?

**Comment by MerlijnWajer** [comment] 2020-01-12 12:11
@eschwelgin - regarding your battery, just leave the device attached to a wall charger for a while. It should get enough power to boot all the way. That said - I'm uploading images today, so might want to wait for those too.

**Comment by ruleh** [comment] 2020-01-23 20:56
It seems like on the droid4 the enter key starts working as expected when the slide-open gconf setting is set to true. Otherwise it tries to toggle the virtual keyboard if that is enabled in the settings.

**Comment by spinal84** [comment] 2020-01-24 03:22
Fixed by https://github.com/maemo-leste/hildon-input-method-framework/commit/a236219e53a1b0d5d2b4cf8174329e9be905bd17

**Comment by freemangordon** [comment] 2020-01-24 07:03
I don't think this is the correct fix unless I am given some evidence.

@spinal84 - please, before pushing changes to frameworks that change the way it work, lets discuss if the change is reasonable and what side effects it might have

**Comment by SimonIremonger** [comment] 2020-01-26 17:59
I note, in the short-term, the change to libhildon etc. appears to have worked, a fully updated leste does indeed give helpfully working keyboard enter key in osso-xterm.

However, I wish to raise a pragmatic (and maybe sensible?) compromise, given concerns above.
What about, instead of 'losing' this code in hildon-input-method, restore it, but make it respond to F24 key (or possibly some hardware PC key like printscreen or scrolllock or pause if supported) in the X11/GTK stack.

In this way, if there is future wish to support N800/N810 [not sure if kernel support forthcoming....] or a device with similar hardware d-pad, it is a simple matter of changing the x11-keymap (for example rx-44 file <KPEN> mapping) to map to F24 pc-style-key and voila, you have your d-pad button function back, most-likely!.

The places I foresee possible complications, come if there is 'other' code which also has directly the special-handling of Enter key at X11/gtk level....  But in general I strongly support this change to fix the classic "broken UI spec" as the original developers put-it!.

**Comment by freemangordon** [comment] 2020-01-26 21:50
> I note, in the short-term, the change to libhildon etc. appears to have worked, a fully updated leste does indeed give helpfully working keyboard enter key in osso-xterm.
> 
> However, I wish to raise a pragmatic (and maybe sensible?) compromise, given concerns above.
> What about, instead of 'losing' this code in hildon-input-method, restore it, but make it respond to F24 key (or possibly some hardware PC key like printscreen or scrolllock or pause if supported) in the X11/GTK stack.
> 

I was thinking about the same, however, I am yet to find a key that is common to all the variety of devices we hope to support. Or, maybe extend hildon-input-method-configurator to set another gconf key ("show_vkb_key"?) based on the particular device it is executed on, with some default (third android devices button?)

> In this way, if there is future wish to support N800/N810 [not sure if kernel support forthcoming....] or a device with similar hardware d-pad, it is a simple matter of changing the x11-keymap (for example rx-44 file KPEN mapping) to map to F24 pc-style-key and voila, you have your d-pad button function back, most-likely!.
> 

Agree. 

> The places I foresee possible complications, come if there is 'other' code which also has directly the special-handling of Enter key at X11/gtk level.... But in general I strongly support this change to fix the classic "broken UI spec" as the original developers put-it!.

I don't think there is anything outside HIM, but even if there is, we can fix it if we hit it.

**Comment by SimonIremonger** [comment] 2020-01-27 00:36
I do think it needs to be switchable to be useful across more devices than specific d-pad-on-n8x0.
However, "for now", can you re-instate the code/patches with GDK_KEY_F24 as the key for now, so we can 'test' this on leste images?....

**Comment by freemangordon** [comment] 2020-01-28 22:05
Does anybody know what GDK_KEY(s) (if any) are those android buttons reported as? What I am thinking is to use this 'three lines' android button to be the default to bring vkb up. So, my idea:

- If there is no 'show_vkb_key' in gconf, use the default key (whatever it is)
- If there is 'show_vkb_key' in gconf, it could be in form of 'KEY1+KEY2+KEY3+...+KEYn' to be able to support not only simple keys, but key combos as well. Maybe limit n to 32 to be able to use a single unsigned int to track combo state.
- modify hildon-input-method-configurator to set appropriate key(s) for the recognized devices.

If you think this is an overkill, please share a more simple solution.

**Comment by spinal84** [comment] 2020-01-29 00:31
1. What is the point of having a hardware key for opening VKB?
2. How does fixing broken Enter key spec prevent you from adding new functionality later? Are you still going to connect it somehow to Enter key press/release events? Please, explain.

**Comment by freemangordon** [comment] 2020-01-29 06:36
>     1. What is the point of having a dedicated hardware key for showing VKB? I mean the tapping somewhere on the screen seems enough.
> 

It is not, there should be edit field to tap in. I'll give you an example - OpenMediaPlayer, with closed keyboard, click on "Music". Now you're presented with a list of songs, however you can't filter through it without typing on the HW keyboard. One might argue that this is a deficiency in OMP, however if you can interact with the device in such a way that VKB is shown, you'll be able to filter even without having to modify OMP. 

>     2. How does fixing broken Enter key spec prevents you from adding new functionality later? Are you still going to connect it somehow to Enter key press/release events? Please, explain.

What is the new functionality to be added later? If you mean "pop VKB on a special key press" - this is not a new functionality, it is already here (albeit broken on devices it was not intended to run on). And I am against removing it just because it is easier for us in a short term.

Please, lets focus on how to fix the non-working "Enter" while keeping the "pop VKB" functionality there.  Your commit a236219 in some shape will most probably be a part of such a solution, so your work won't be in vain. But, I want to have a clear view/direction first, modifying the code once we have that is the most easy part.

**Comment by spinal84** [comment] 2020-01-29 13:55
> What is the new functionality to be added later? If you mean "pop VKB on a special key press" - this is not a new functionality, it is already here (albeit broken on devices it was not intended to run on). And I am against removing it just because it is easier for us in a short term.

As I'm N900 user, for me this is a new functionality, probably like for many others. About your "I am against removing it...", I remove bug, not the functionality (which is broken as you already mentioned). You can always sit in the time machine go back and see how it worked on N8xx devices, just use "git log && git checkout ..." commands. But for now, removing that _broken_ part fixes at least two things: double enter in virtualbox and vkb popup in droid4/n900 with remapped Enter (https://github.com/maemo-leste/bugtracker/issues/308). I don't see a serious point in delaying this fix.

**Comment by IMbackK** [comment] 2020-01-29 23:13
This seams fixed now after repo upgrade.

**Comment by freemangordon** [comment] 2020-01-30 06:54
@spinal84: this is not productive. You either come up with code that fixes the issue without removing the functionality in question or come up with idea on how to fix the issue without removing that functionality. Or at least comment on other's ideas so far. Bringing your personal habits or preferences on the table doesn't help.

BTW, I am N900 user as well and I have never seen N8x0 in the RL. But that means nothing in the context of the issue.

**Comment by freemangordon** [comment] 2020-01-30 07:02
> I do think it needs to be switchable to be useful across more devices than specific d-pad-on-n8x0.
> However, "for now", can you re-instate the code/patches with GDK_KEY_F24 as the key for now, so we can 'test' this on leste images?....

I'll try to come-up with something during the weekend.

Do I get it right that you choose GDK_KEY_F24 because there is no way for it to be pressed?

**Comment by spinal84** [comment] 2020-01-30 07:56
One last note.

@freemangordon, do you remember what the issue was?
Droid 4 - Hardware key not working [Enter]

The fix is ready. It doesn't break anything, it doesn't do something bad. And it doesn't prevent you from adding (or fixing) the functionality you want to have. It doesn't prevent you from adding it in the weekend, or the next month, or the next year, or never.

I may be wrong, but you had at least 2 months to implement or fix whatever feature you wanted. The fix for Enter key is ready. And what you wanna to do is another issue (vkb not popping up on some weird hardware key combos). This one should be closed, IMHO.

To others who don't understand, what I'm talking about. There's one additional commit needed to complete the fix (https://github.com/maemo-leste/hildon-input-method/pull/1) which @freemangordon denied. What this commit does, is removing broken functionality which prevents Enter key presses to be handled properly. Without it the fix is semi-implemented. You have a working Enter key on Droid4, but you also have broken functionality in VirtualBox and on Droid4 with VKB enabled.

There's no reason to deny or delay the fix. We are ready to wait for you mr. @freemangordon to have your job done (even if it's something we'll never use). But why should we delay what already has done?

**Comment by SimonIremonger** [comment] 2020-01-30 09:57
> > I do think it needs to be switchable to be useful across more devices than specific d-pad-on-n8x0.
> Do I get it right that you choose GDK_KEY_F24 because there is no way for it to be pressed?
Essentially yes, this i a key that simply doesn't exist on all but the most unusually large PC keyboards that might be attached.
For n8xx you can simply change the [I think] rx-44 keymap to map their d-pad central key TO F24, thereby making it work with code expecting F24 to be pressed.
However, as others pointed out, keys to activate vkb really will need to be more 'selectable' in order to work across range of leste devices.  @freemangordon Please do create a new issue with suggested solutions, suggested keys on devices etc. if you want to start that process.

In any case, I 100% agree this 'enter key nobbling' should be seen as separate and should now be closed please, unless any unexpected-issues come-up at this point!.

**Comment by MerlijnWajer** [comment] 2020-01-30 13:07
I'd like to stress that, unlike what I portray most of the time, we're not in a rush. I am fine waiting until the weekend. We've already been at this for over two years (! :) ), what's a few more days?

Yes, we can merge a fix, but if FMG says he wants to take a look in the weekend - I am perfectly fine waiting a few more days. It's not like this wasn't broken for, how long, like 2 years? ;)

**Comment by freemangordon** [comment] 2020-01-30 19:02
And I guess we should have lot less heated conversation if somebody did spend some time on reading the code first:

Return key triggers VKB only if either /system/osso/af/slide-open or /system/osso/af/keyboard-attached is set to true and VKB is enabled in control panel. If any of those keys is true, Return key behaves exactly like Enter key. If both keys are false, but VKB is not enabled, Return key is ignored (which is reported as a bug).

Since ke-recv patch that enables SLIDE monitoring is still under review and droid4 is not recognized by hildon-input-method-configurator (see https://github.com/maemo-leste/hildon-input-method-configurator/blob/master/src/configurator.c#L93) what I can guess is that both keys are false and by default VKB is not enabled in control panel. This is a combination that is not expected (and thus not handled) by HIM, thus the 'bug'.

So, the correct fix is - 'Do not try to show VKB if it is disabled and both slide-open and keyboard-attached are false, behave as if there is HW keyboard instead'. The code there https://github.com/maemo-leste/hildon-input-method/blob/master/src/hildon-im-ui.c#L1354 should be changed like this https://github.com/maemo-leste/hildon-input-method/pull/3/commits/f01d4721c9bc65202cb2f601f815f7e8c797d8c2#diff-bfd5ed1e336bb126cefa564a735580bbR1354

So, this https://github.com/maemo-leste/hildon-input-method-framework/commit/a236219e53a1b0d5d2b4cf8174329e9be905bd17 must be reverted.

**Comment by spinal84** [comment] 2020-01-31 10:12
Replied here: https://github.com/maemo-leste/hildon-input-method-framework/commit/a236219e53a1b0d5d2b4cf8174329e9be905bd17#commitcomment-37056274

**Comment by freemangordon** [comment] 2020-01-31 12:52
@spinal84: do not spread FUD. And again, you have your second warning to lower your attitude!

**Comment by spinal84** [comment] 2020-01-31 14:31
@freemangordon did a good job on fixing the issue the correct way.

It seems I forgot about some debugging code I added to vte/xterm, so it could interfere with @freemangordon fix. After doing Maemo Leste fresh install Enter key seems to be working as expected on Droid4.

My apologies for the hassle.

**Comment by spinal84** [comment] 2020-02-01 11:59
Enyc and @MerlijnWajer reported that after implementing the fix from https://github.com/maemo-leste/hildon-input-method/pull/3 they have issues with Enter remapped to Return on N900 devices: the Enter keypresses are ignored. I checked that and can confirm this behaviour too.

With these two things applied it worked as expected:
https://github.com/maemo-leste/hildon-input-method-framework/commit/a236219e53a1b0d5d2b4cf8174329e9be905bd17
https://github.com/maemo-leste/hildon-input-method/pull/2

On Droid4 (which maps Enter to Return by default) it seems to work as expected.
Connected issue: https://github.com/maemo-leste/bugtracker/issues/308

I'm reopening the issue until we have fix for this.

**Comment by freemangordon** [comment] 2020-02-01 15:50
The problem comes from the fact with the modified keyboard map, no keyval is mapped to KP_Enter key, so the code here https://github.com/maemo-leste/hildon-input-method-framework/blob/master/src/hildon-im-context.c#L1339 and https://github.com/maemo-leste/hildon-input-method-framework/blob/master/src/hildon-im-context.c#L245 cannot find keycode to fake the requested key. 

if keyboard is done like:

    key <RTRN>	{ [	Return		] };
    key <KPEN>	{ [	KP_Enter	] };

so hildon-input-method-framework to be able to map KP_Enter to keyval, everything works as expected

**Comment by spinal84** [comment] 2020-02-02 17:58
The bug returned with today's updates.
```
hildon-input-method                            1:2.1.52-1+1m7
hildon-input-method-framework:armhf            1:2.1.66-1+1m7
```

**Comment by freemangordon** [comment] 2020-02-02 18:39
@spinal84 - do you know who rebuild the packages? As it seems to me the problem is that h-i-m was rebuild with the older version of hildon-input-method-framework. If h-i-m is rebuild with the h-i-m-fw in the repo, everything works.

**Comment by freemangordon** [comment] 2020-02-02 18:47
I am sorry about that, it is my fault, I should have provided the correct dependency in debian/control. Going to fix that.

**Comment by freemangordon** [comment] 2020-02-03 10:51
@spinal84 correctly build h-i-m (version 1:2.1.53-1+1m7)  is in the repo, please upgrade and test

**Comment by SimonIremonger** [comment] 2020-02-03 13:57
@freemangordon  @spinal84   Have upgraded to that h-i-m (and libhildon-im-ui3)   on n900 and confirm the issue is NOT fixed, still having to ctrl-M instead of Return in  osso-xterm .....

**Comment by SimonIremonger** [comment] 2020-02-03 14:28
FWIW I looked back in my IRC history with danels and so on, who was apparently original layout author and vaguely-recalls the keymap-setting-up issues of the past, says about the Return/KP_Enter on nokia:-

But it was something to do with UI and activating things - like if you pressed enter on the internal keyboard that may be closer evidence that you wanted to go to the next page, rather than insert a carriage return
It was deliberately made separate from normal Return in order to do _something_ different when the key was pressed on the  internal kb compared to an external one
I _think_ the middle 'select' button in the N8x0 four-way D-pad sends Return
Return was specified to mean 'do the action on the currently-selected button, _or_ if it's a text field then bring up the text input method (e.g. on-screen keyboard)'
So then for the actual physical keyboard which had an Enter key which we always wanted to mean a newline, we had to use KP_Enter because Return's function was ambiguous

Also, pointed out  "Polish used a normal US layout, and all special characters were accessed with combining keys" ..
The above may help with some of the ''research'' into hildon code/behaviour.

**Comment by freemangordon** [comment] 2020-02-03 16:42
I just upgraded on my n900 and can confirm that the issue IS fixed, key mappings are:

    key <RTRN>	{ [	Return		] };
    key <KPEN>	{ [	KP_Enter	] };

**Closed by freemangordon** 2020-02-03 16:42 UTC

**Comment by spinal84** [comment] 2020-02-03 18:07
I can reliably reproduce the issue. For this, one should start osso-xterm as fast as possible after system boots (use the stylus not to miss). If he does so, the remapped Enter key will stop working. Ctrl-Enter will work as expected. On Droid4 it's pretty hard to reproduce because of slow UI, but on Nokia N900 it can be done reliably.

As a temporary fix, a user should wait a bit after system startup, or try to restart osso-xterm if the issue appeared. I think the issue is connected to init system Maemo Leste uses.

@SimonIremonger, about your last two messages. The keymap you are using was working fine with the broken UI spec. which was the legacy from the pre-Fremantle times. @freemangordon made some changes recently to fix the wrong behaviour, so there's no need in that broken spec. anymore. But the new approach doesn't work correctly, if you don't have appropriate KP_Enter entry in your keymap. You will have to edit your keymap manually or ask Enyc to fix his keymap version, so you can just download updated version.

If you want to do this manually, just replace `key <KPEN> ... ;` entry in your keymap file with this `key <KPEN>	{ [	KP_Enter	] };`. The file with the keymap is located here: /usr/share/X11/xkb/symbols/nokia_vndr/rx-51

Please let us know, if you still have problems with Enter key handling in Maemo Leste.

**Comment by SimonIremonger** [comment] 2020-02-03 21:04
Keymap above fixed and should soon make its' way into Leste, Wizzup working on.
The "enter key not working soon after boot" can indeed occur, this may be in part related to h-i-m internal Return/KP_Enter swapping behaviour, which may be subject of a separate bug-report =).
However, the key blocking issues are sorted, even if h-i-m "not fully right yet", @freemangordon pointed out better things to be doing at the moment...

**Comment by freemangordon** [comment] 2020-02-03 21:18
The "enter key not working soon after boot" is most probably related to dbus unable to start hildon-input-method in time, maybe we shall pre-start it from Xsession.post. I'll take a look at the issue though.

**Comment by SimonIremonger** [comment] 2020-02-03 21:42
Have opened new issue #316 to cover these ongoing fixes in hildon-input-method.  This bug #263 should be seen as closed for now, I confirm latest h-i-m  1:2.1.52-1+1m7.1  fixes enter not working at all issue.  Leste n900 keymap should soon be updated too.

**Comment by spinal84** [comment] 2020-02-13 12:55
There's one additional issue connected to hardware Enter key handling (reported by @SimonIremonger):

>  open osso-xterm, then "dmesg | less" then "/test" then try to press hardware enter, you will get silly "ESCOM" or so, as H-I-M isn't sending proper code through.
> Alternatively, "apt-get -y install tf5" then in osso-xterm run "tf5" and try to press enter, complains about nkpEnt

With those two things applied it works as expected:
maemo-leste/hildon-input-method-framework@a236219
maemo-leste/hildon-input-method#2

For now there are two side effects with the currently used approach (the second one is about osso-xterm started immediately after boot).

**Comment by IMbackK** [comment] 2020-03-28 12:45
> I can reliably reproduce the issue. For this, one should start osso-xterm as fast as possible after system boots (use the stylus not to miss). If he does so, the remapped Enter key will stop working. Ctrl-Enter will work as expected. On Droid4 it's pretty hard to reproduce because of slow UI, but on Nokia N900 it can be done reliably.
> 
> As a temporary fix, a user should wait a bit after system startup, or try to restart osso-xterm if the issue appears. I think the issue is connected to the init system Maemo Leste uses. But can also be fixed in hildon-input-method sources.
> 
> @SimonIremonger, about your last two messages. The keymap you are using was working fine with the broken UI spec. which was the legacy from the pre-Fremantle times. @freemangordon made some changes recently to fix the wrong behaviour, so there's no need in that broken spec. anymore. But the new approach doesn't work correctly, if you don't have appropriate KP_Enter entry in your keymap. You will have to edit your keymap manually or ask Enyc to fix his keymap version, so you can just download updated version.
> 
> If you want to do this manually, just replace `key <KPEN> ... ;` entry in your keymap file with this: `key <KPEN> { [ KP_Enter ] };`. The file with the keymap is located here: /usr/share/X11/xkb/symbols/nokia_vndr/rx-51
> 
> Please let us know, if you still have problems with Enter key handling in Maemo Leste.

I can still reproduce via this method on droid 4 on latest 20200323 with apt updates as of today

**Comment by MerlijnWajer** [comment] 2020-04-06 21:55
I wonder if this also happens if you let the device boot, wait for 5 minutes or so, and then try again.
