### ISSUE TITLE
Migrate to debhelper 10 for beowulf and parallel builds

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#234] opened 2019-03-29 12:33 UTC
Parazyd said we need to use debhelper for all our packages, and that the beowulf version will automatically use parallel build / multiple jobs.

**Comment by parazyd** [comment] 2019-03-30 09:38
We should also update older packages to compat 9 or even compat 10.

Here's a list of packages that should port to debian/compat <9

- [ ] https://github.com/maemo-leste/alarmd
- [ ] https://github.com/maemo-leste/cityinfo
- [ ] https://github.com/maemo-leste/clipboard-manager
- [ ] https://github.com/maemo-leste/clockd
- [ ] https://github.com/maemo-leste/codelockui
- [ ] https://github.com/maemo-leste/connui-internet
- [ ] https://github.com/maemo-leste/connui-wlan
- [ ] https://github.com/maemo-leste/epeg
- [ ] https://github.com/maemo-leste/gtk
- [ ] https://github.com/maemo-leste/hildon-control-panel
- [ ] https://github.com/maemo-leste/hildon-desktop
- [ ] https://github.com/maemo-leste/hildon-home
- [ ] https://github.com/maemo-leste/hildon-im-vkbrenderer3
- [ ] https://github.com/maemo-leste/hildon-initscripts
- [ ] https://github.com/maemo-leste/hildon-input-method-framework
- [ ] https://github.com/maemo-leste/hildon-input-method-plugins
- [ ] https://github.com/maemo-leste/hildon-input-method
- [ ] https://github.com/maemo-leste/hildon-plugins-notify-sv
- [ ] https://github.com/maemo-leste/hildon-status-bar-usb
- [ ] https://github.com/maemo-leste/hildon-status-menu
- [ ] https://github.com/maemo-leste/hildon-theme-cacher
- [ ] https://github.com/maemo-leste/hildon-thumbnail
- [ ] https://github.com/maemo-leste/icd2-osso-ic-dev
- [ ] https://github.com/maemo-leste/iphbd
- [ ] https://github.com/maemo-leste/ke-recv-extra
- [ ] https://github.com/maemo-leste/libcal
- [ ] https://github.com/maemo-leste/libconic
- [ ] https://github.com/maemo-leste/libdevlock
- [ ] https://github.com/maemo-leste/libdsme
- [ ] https://github.com/maemo-leste/libhildondesktop
- [ ] https://github.com/maemo-leste/libhildonfm
- [ ] https://github.com/maemo-leste/libhildonmime
- [ ] https://github.com/maemo-leste/libimengines
- [ ] https://github.com/maemo-leste/libimlayouts
- [ ] https://github.com/maemo-leste/libmatchbox2
- [ ] https://github.com/maemo-leste/libplayback
- [ ] https://github.com/maemo-leste/maemo-launcher
- [ ] https://github.com/maemo-leste/maemo-security-certman-applet
- [ ] https://github.com/maemo-leste/maemo-security-certman
- [ ] https://github.com/maemo-leste/n9xx-linux
- [ ] https://github.com/maemo-leste/n9xx-xf86-video-fbdev-sgx
- [ ] https://github.com/maemo-leste/osso-af-settings
- [ ] https://github.com/maemo-leste/osso-app-killer
- [ ] https://github.com/maemo-leste/osso-applet-devicelock
- [ ] https://github.com/maemo-leste/osso-applet-display
- [ ] https://github.com/maemo-leste/osso-applet-notificationlight
- [ ] https://github.com/maemo-leste/osso-bookmark-engine
- [ ] https://github.com/maemo-leste/osso-icons
- [ ] https://github.com/maemo-leste/osso-product-info
- [ ] https://github.com/maemo-leste/osso-systemui-alarm
- [ ] https://github.com/maemo-leste/osso-systemui-dbus-dev
- [ ] https://github.com/maemo-leste/osso-systemui-devlock-dev
- [ ] https://github.com/maemo-leste/osso-systemui-modechange-dev
- [ ] https://github.com/maemo-leste/osso-systemui-powerkeymenu
- [ ] https://github.com/maemo-leste/osso-systemui-splashscreen-dev
- [ ] https://github.com/maemo-leste/osso-systemui-tklock
- [ ] https://github.com/maemo-leste/osso-systemui
- [ ] https://github.com/maemo-leste/osso-xterm
- [ ] https://github.com/maemo-leste/profiled
- [ ] https://github.com/maemo-leste/sapwood
- [ ] https://github.com/maemo-leste/status-area-orientationlock-applet
- [ ] https://github.com/maemo-leste/status-menu-applet-profiles
- [ ] https://github.com/maemo-leste/statusbar-alarm-dbus-api
- [ ] https://github.com/maemo-leste/sysinfod ?
- [ ] https://github.com/maemo-leste/ukeyboard
- [ ] https://github.com/maemo-leste/wl1251-cal
- [ ] https://github.com/maemo-leste/xserver-xorg-video-fbdev

**Comment by parazyd** [comment] 2019-03-30 09:47
This could be related as well: https://github.com/maemo-leste/bugtracker/issues/66

**Comment by spinal84** [comment] 2019-03-30 15:51
xserver-xorg-video-fbdev can be deleted, it's replaced by xf86-video-pvrsgx

**Comment by spinal84** [comment] 2019-03-30 15:56
I suggest to add changes to maemo/ascii-devel first. And move to maemo/ascii after a while (about 2 weeks of testing should be fine).

**Comment by parazyd** [comment] 2019-03-30 15:57
Okay, agreed. I'll proceed with doing them for maemo/ascii-devel!

Also you're right about `--parallel` being default in compat 10.

Thanks.

**Comment by spinal84** [comment] 2019-03-31 13:38
@parazyd, please don't update master branch of repositories. This branch is only for tested changes.
The work flow should be like this:
1) Upload your changes to maemo/ascii-devel branch
2) Build the package in Jenkins
3) Test your changes for a while (about 2 weeks should be fine)
4) Do merge request to master branch
5) Other people will check what you've done, discuss your work and propose how to make it better
6) If everything is ok, your is merged to master branch
7) From master branch it goes then to maemo/ascii branch
8) Jenkins build is scheduled to make your changes go to stable repo.

**Comment by spinal84** [comment] 2019-03-31 14:02
An example of bad workflow.
1. You changed GTK repository master branch yesterday.
2. I think, you didn't notice the master branch was 10 commits behind maemo/ascii branch.
3. In such a situation maemo/ascii should have been merged prior to any further work on the repo.
4. But the changes that you single-handedly approved to master branch will now conflict to what's done in maemo/ascii branch.
5. Now someone is forced to resolve the conflicts you added to the repository. That is time consuming and not very productive work.

**Comment by MerlijnWajer** [comment] 2019-04-01 15:35
I am not sure if we should test dh changes for two weeks, we're not yet in alpha phase. I personally don't have time at least to review all the changes everyone makes, too. But going to `maemo/ascii-devel` first definitely makes sense. I assume that eventually we will want maintainers for specific subsystems/components, so we know who to look at / ask for review. Let's follow up in #240.

**Comment by spinal84** [comment] 2019-04-01 16:24
> I am not sure if we should test dh changes for two weeks, we're not yet in alpha phase.

Could you please explain, what do you mean:
1) Should we test changes for about 1 week before moving to stable?
OR
2) Should we skip testing at all?

Migrating to dh sequencer and updating debian compat level to 10 is not such a trivial task as it may seem.

Of course, if we are just going to remove all the contents from debian/rules files and replace it with
```
#!/usr/bin/make -f
%:
        dh $@
```
... without fully understanding why those commands (and CFLAGS) were there. And even no further testing is needed before moving to master branch. I can't agree with such approach.

P.S. Personally I don't really understand why are we forced to move all packages to compat level 10. We could do it one by one gradually as more important changes are made to the packages. 
Without making mistakes in a hurry.

**Comment by MerlijnWajer** [comment] 2019-04-01 19:27
I think we should not skip the devel stage. Just that two weeks might a bit excessive. But I'm fine with it either way.

What weird CFLAGS did you encounter?

Moving the packages to compat level 10 would be nice when we move to newer Debian/Devuan release and also for parallel builds.

**Comment by spinal84** [comment] 2019-04-01 20:34
It's not about CFLAGS weirdness, it's about silently skipping debug/thumb flags which were present in original debian/rules.

The flags were removed. It should be explained/documented in commit message. Or are we doing a quickie? I think it's better to have a separate commit for every logical change we have.

**Comment by MerlijnWajer** [comment] 2019-07-26 21:03
Finished libhildonmime. Please review package contents vs old one.

**Comment by MerlijnWajer** [comment] 2019-07-27 11:02
I've done cityinfo, clockd, libosso, icd2-osso-ic-dev, libconic, osso-systemui-dbus-dev, libdsme -- all of them could use review. Going to continue and will post updates as I go along.

**Comment by MerlijnWajer** [comment] 2019-07-27 11:14
statusbar-alarm-dbus-api done

**Comment by MerlijnWajer** [comment] 2019-07-27 13:17
We're currently at this line, all the other packages still need porting and/or building:

https://github.com/maemo-leste/jenkins-integration/blob/master/config.py#L75

To anyone wanting to help out: it'd be good to take any package below line 75 and see if it's already ported to dh 10. This can be done on ascii/leste, doesn't need to be done one beowulf/bayamo.

**Comment by MerlijnWajer** [comment] 2020-01-08 17:45
`hildon-initscripts` done
`osso-af-settings` done

Please verify if what I did is correct. I will do a lot more if you guys can agree with the way I'm doing this.

**Comment by MerlijnWajer** [comment] 2020-01-08 18:02
`ke-recv-extra` also done.

Please verify it, and let's also merge it to master if it's OK.

**Comment by MerlijnWajer** [comment] 2020-01-08 18:10
`clipboard-manager` also does. Going to stop for a bit and wait for review.

I kind of assumed `-Wall -g` and others would be *default* CFLAGS for Debian, but they don't ... seem to be? Might have to go over some of the packages I just did and see why they are not added, and add them again to `debian/rules` if that's how it's supposed to be done.

**Comment by spinal84** [comment] 2020-01-08 22:38
I usually compare the contents of resulting deb package after migration to newer debhelper with the old one. It's probably the easiest way to see if something has gone wrong.

**Comment by MerlijnWajer** [comment] 2020-01-08 22:52
Yeah, for the above four packages the contents is the same. I just expected it Debian to have it's own default CFLAGS like `-Wall -g` or something. Or -`O2`, etc. And I'm just not seeing that at all, look here for example:

https://phoenix.maemo.org/job/clipboard-manager-binaries/lastBuild/architecture=amd64,label=amd64/console

**Comment by MerlijnWajer** [comment] 2020-01-08 22:53
Hrm:

```
# dpkg-buildflags --query
Vendor: Devuan
Environment:

Flag: CFLAGS
Value:
Origin: vendor

Flag: CPPFLAGS
Value:
Origin: vendor

Flag: CXXFLAGS
Value:
Origin: vendor

Flag: FCFLAGS
Value:
Origin: vendor

Flag: FFLAGS
Value:
Origin: vendor

Flag: GCJFLAGS
Value:
Origin: vendor

Flag: LDFLAGS
Value:
Origin: vendor

Flag: OBJCFLAGS
Value:
Origin: vendor

Flag: OBJCXXFLAGS
Value:
Origin: vendor
```

**Comment by spinal84** [comment] 2020-01-08 23:13
For future references, this is about how to properly use custom CFLAGS in debian/rules file:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923626

**Comment by MerlijnWajer** [comment] 2020-01-08 23:16
@spinal84 - if you have a debian install, can you run `dpkg-buildflags --query` and see if it's any different?

**Comment by spinal84** [comment] 2020-01-08 23:21
```
$ dpkg-buildflags --query
dpkg-buildflags: error: unknown option '--query'

Use --help for program usage information.
```

**Comment by spinal84** [comment] 2020-01-08 23:21
```
$ dpkg-buildflags --status
dpkg-buildflags: status: vendor is Debian
dpkg-buildflags: status: hardening features: bindnow=no format=yes fortify=yes pie=yes relro=yes stackprotector=yes stackprotectorstrong=yes
dpkg-buildflags: status: qa features: bug=no canary=no
dpkg-buildflags: status: reproducible features: fixdebugpath=yes timeless=yes
dpkg-buildflags: status: sanitize features: address=no leak=no thread=no undefined=no
dpkg-buildflags: status: CFLAGS [vendor]: -g -O2 -fdebug-prefix-map=/home/spinal=. -fstack-protector-strong -Wformat -Werror=format-security
dpkg-buildflags: status: CPPFLAGS [vendor]: -Wdate-time -D_FORTIFY_SOURCE=2
dpkg-buildflags: status: CXXFLAGS [vendor]: -g -O2 -fdebug-prefix-map=/home/spinal=. -fstack-protector-strong -Wformat -Werror=format-security
dpkg-buildflags: status: FCFLAGS [vendor]: -g -O2 -fdebug-prefix-map=/home/spinal=. -fstack-protector-strong
dpkg-buildflags: status: FFLAGS [vendor]: -g -O2 -fdebug-prefix-map=/home/spinal=. -fstack-protector-strong
dpkg-buildflags: status: GCJFLAGS [vendor]: -g -O2 -fdebug-prefix-map=/home/spinal=. -fstack-protector-strong
dpkg-buildflags: status: LDFLAGS [vendor]: -Wl,-z,relro
dpkg-buildflags: status: OBJCFLAGS [vendor]: -g -O2 -fdebug-prefix-map=/home/spinal=. -fstack-protector-strong -Wformat -Werror=format-security
dpkg-buildflags: status: OBJCXXFLAGS [vendor]: -g -O2 -fdebug-prefix-map=/home/spinal=. -fstack-protector-strong -Wformat -Werror=format-security
```

**Comment by MerlijnWajer** [comment] 2020-01-08 23:21
Compare to Devuan:

```
# dpkg-buildflags --status
dpkg-buildflags: status: vendor is Devuan
dpkg-buildflags: status: CFLAGS [vendor]:
dpkg-buildflags: status: CPPFLAGS [vendor]:
dpkg-buildflags: status: CXXFLAGS [vendor]:
dpkg-buildflags: status: FCFLAGS [vendor]:
dpkg-buildflags: status: FFLAGS [vendor]:
dpkg-buildflags: status: GCJFLAGS [vendor]:
dpkg-buildflags: status: LDFLAGS [vendor]:
dpkg-buildflags: status: OBJCFLAGS [vendor]:
dpkg-buildflags: status: OBJCXXFLAGS [vendor]:
```

**Comment by MerlijnWajer** [comment] 2020-01-08 23:26
Well, I think I'll continue porting some more packages and assume Devuan will fix this, and then we can re-build all ours. Or use Debian, we'll see.

But it seems they still lack `-Wall`, so adding `-Wall` to (all C/C++) packages is probably something we want to do. Agreed?

**Comment by spinal84** [comment] 2020-01-08 23:30
I doubt that adding workarounds to debian/rules files because some distro has weird issues in debian build system is a good idea.

**Comment by MerlijnWajer** [comment] 2020-01-08 23:31
Right, but Debian also lacks `-Wall` per your own paste. I think we'll always want to have `-Wall`.

**Comment by MerlijnWajer** [comment] 2020-01-08 23:31
BTW, maybe we can do some of this on IRC?

**Comment by spinal84** [comment] 2020-01-08 23:32
Sorry I didn't get it right. Adding -Wall is always a good idea :)

**Comment by spinal84** [comment] 2020-01-15 23:23
And this is about making packages multi-arch aware:
https://wiki.debian.org/Multiarch/Implementation

The important part is adding "Multi-arch" section to packages in debian/control file. It may be:
Multi-Arch: foreign
Multi-Arch: same

Please read the article to get idea about the difference.

**Comment by Daniel-Abrecht** [comment] 2020-01-16 19:21
I already reported the dpkg-buildflags problem, the root cause, and a potential solution, a few months ago, here: https://bugs.devuan.org/cgi/bugreport.cgi?bug=353

**Comment by MerlijnWajer** [comment] 2020-01-18 10:22
@spinal84 - I will start adding Multi-Arch to packages I port from now on, where it makes sense.

**Comment by MerlijnWajer** [comment] 2020-01-18 10:22
@parazyd - should we just patch our jenkins build systems and maemo systems with the above?

**Comment by MerlijnWajer** [comment] 2020-01-18 10:46
@spinal84  Maybe we can work on a checklist:

Porting to debhelper 10:

1. Ensure that package contents before and after is the same.
2. Remove `-dbg` package, debian will create `-dbgsym` automatically
3. Get rid of most boilerplace, but keep configure flags in mind.
4. Get rid of arm thumb specific flags
5. Add specific `-Werror` or `-Wno-bla` flags to `DEB_CFLAGS_APPEND` and `export` it.
6. Add `Multi-Arch: same` to `Architecture: any` packages, and `Multi-Arch: foreign` to `Architecture: all` packages.
7. Change `debian/compat` to be 10.

Stuff like that. Maybe we can also link to some example packages where basically all of this is done. (libhildondesktop might get close at this point) ?

**Comment by spinal84** [comment] 2020-01-18 11:05
> 6. Add `Multi-Arch: same` to `Architecture: any` packages, and `Multi-Arch: foreign` to `Architecture: all` packages.

Overall idea is good. Just keep in mind, if you have issues with Multi-Arch fields, they are not limited to only two values:
https://wiki.ubuntu.com/MultiarchSpec#Binary_package_control_fields

**Comment by spinal84** [comment] 2020-01-18 12:44
> 5. Add specific `-Werror` or `-Wno-bla` flags to `DEB_CFLAGS_APPEND` and `export` it.

It's better to use DEB_CFLAGS_MAINT_APPEND instead. DEB_CFLAGS_APPEND use is prohibited by dpkg-buildflags manual page (check ENVIRONMENT section):
http://man7.org/linux/man-pages/man1/dpkg-buildflags.1.html

Here's the quote:
> There are 2 sets of environment variables doing  the  same  operations,
> the  first  one (DEB_flag_op) should never be used within debian/rules.
> It's meant for any user that wants to rebuild the source  package  with
> different  build  flags. The second set (DEB_flag_MAINT_op) should only
> be used in debian/rules by package maintainers to change the  resulting
> build flags.

**Comment by spinal84** [comment] 2020-01-18 13:16
About examples, I'd better take this one: https://github.com/spinal84/hildon-desktop
The commit list to check:
https://github.com/spinal84/hildon-desktop/commit/ae4fdfe7c1367ecb8525795ba851ceacc6017463
https://github.com/spinal84/hildon-desktop/commit/33625343c1f7b47a07aaa2a9bae3e70e06ceef73
https://github.com/spinal84/hildon-desktop/commit/858a17c32311c33aedebb68f939273d9b30ff33f
https://github.com/spinal84/hildon-desktop/commit/282341ffc5661ee93a746bb20bff9ec22751e3f6
https://github.com/spinal84/hildon-desktop/commit/8050046c071ce92c2f2e924e3c400744ab38320f
https://github.com/spinal84/hildon-desktop/commit/592ab8b61469aaa1940aff93286ec29c8f59d841
https://github.com/spinal84/hildon-desktop/commit/0ae67c323bd80d84dd85b059d96fff3de6dc90aa
https://github.com/spinal84/hildon-desktop/commit/08b4b2ff8626f3bed9d69f822a1d05cc1cccdf02

**Comment by MerlijnWajer** [comment] 2020-01-20 14:06
As of right now, I have `hildon-desktop` and `hildon-home` running in a beowulf VM. mce is not yet in the repo since it depends on a patched upower (well, it doesn't depend on it, but for correct functionality, we do)

**Comment by parazyd** [comment] 2020-10-30 16:52
I will close this now, as 90%+ packages are ported, and the rest will be ported on a per-need basis. And obviously new packages already come in as dh10 :)  

Thanks for the effort!

**Closed by parazyd** 2020-10-30 16:52 UTC
Labels: Good starter, Packaging
