### ISSUE TITLE
N900 armel images do not work

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#92] opened 2018-03-02 10:45 UTC
This was reported in the talk.maemo.org thread - likely we just need to fix some powervr library paths.

@dderby - you could provide some additional information?

**Comment by dderby** [comment] 2018-03-03 01:57
The build I tried was "20180207".  I don't really have any more info other than what I already mentioned in the thread.  Here's the link to my post which includes the Xorg.0.log for reference:
https://talk.maemo.org/showpost.php?p=1541078&postcount=37

As I mentioned, the OS shuts down immediately which makes it difficult to debug.  This is possibly caused by the lifeguard reset so it might be a good idea to tackle #89 first.

**Comment by MerlijnWajer** [comment] 2018-03-03 09:42
Just as a general tip, if you're debugging this kind of problems, the easiest thing to do right now is this:

`mv /etc/init.d/dsme{,_}`

And then restart. You'll get dropped into a getty, with sshd and everything, just none of the maemo stuff, and then you can start X manually and see what happens.

For now, don't boher for armel. Regarding lifeguard reset, I think you can also set it using `0xFFFF`?

**Comment by MerlijnWajer** [comment] 2018-03-03 21:10
OK, I tried to make powervr work. But I failed. There were multiple issues, first of all, several libs in /usr/lib were wrong symlinks. I fixed that, but pvrsrvinit_r121 segfaults on first run, and then doesn't want to run afterwards because pvr is "still initialising".

I've reverted to mesa on my image and that works. But yeah.

**Comment by MerlijnWajer** [comment] 2018-03-03 21:12
@freemangordon suggested that we make the armel image mesa only, so that we can at least use it for dev that requires messing with fremantle libs. @parazyd ?

**Comment by MerlijnWajer** [comment] 2018-11-10 11:10
@parazyd - I will see if I can give this another try soon, but otherwise should it make it llvmpipe only.

**Comment by parazyd** [comment] 2020-01-06 20:25
Closing since dead.

**Closed by parazyd** 2020-01-06 20:25 UTC
Labels: N900, armel
