### ISSUE TITLE
N900: overall slowness

### ISSUE THREAD

**Issue by Arno1103** [maemo-leste/bugtracker#737] opened 2024-05-02 16:21 UTC
New DDX and Xorg 16bpp mode improve speed and reactivity a lot compare to last year. But that's still not enough for daily use.
Cpufreq boost mode helps as well (with min freq at 500MHz) for responsiveness but UI is still laggy under certain circumstances, and heavy loads are still a problem.

On TMO, i found old threads about virtual memory tweaks and gnome-tracker issues:
Indeed, blocking trackers on boot help the device a lot. N900 boots a bit faster and most lags in Hildon-Desktop disappear. But tweaks work only if most transitions effects are OFF. Weird, but the root cause is blur effect: if radius and radius_more are set to 0, Hildon-Desktop become amazingly fast on the N900 and most effects can be activated with absolutely no lags or slowdown. This blur issue exists on Fremantle (even with last CSSU) according to TMO by the way.

Few virtual memory settings improve performances too: 
vm.swappiness=30
vm.page-cluster=8
vm.vfs_cache_pressure=200
vm.dirty_ratio=5
vm.dirty_background_ratio=2

And echo 512 > /sys/block/mmcblk0/queue/nr_requests
(with that, device is still usable when i copy a 850MB file from MMC to SDcard, from Leste ofc, it was not possible before).

Now, even  at 600MHz max, there is no slowness anymore but it is a bit frustrating when a Qt5 app takes more than 5 seconds to start.
Qt5 booster could help a lot in my opinion.

Boot time is still too long: 2 min 30 and 1 min 20 to shutdown.

**Comment by IMbackK** [comment] 2024-05-02 18:08
for the (low) standards of a desktop ui, a blur shader  is a pretty expensive shader. what probubly happend here is that the new pvr ddk's shader compiler is doing a bit worse on this particular shader.

**Comment by MerlijnWajer** [comment] 2024-05-04 11:16
I can confirm that the nr_requests change does seem to help (still checking out the other options), unfortunately we might have to set those through some boot script, since we can't set those through sysctl

**Comment by MerlijnWajer** [comment] 2024-05-05 10:01
I added a leste-config-n900 update to chimaera-devel which contains an init script to set the nr_requests and also the sysctl.d values you provided.

@IMbackK also asked on IRC whether we should have these sysctl.d values perhaps set more broadly on more devices, but I'll leave that up to you guys to figure out.

I'm still not quite sure what would be the best way to change the transitions.ini file to remove the blur.

**Comment by Arno1103** [comment] 2024-05-06 17:08
For tracker2, as a reminder and as discussed on IRC, we can add a .nomedia or .trackerignore empty file in the folders we don't want to be tracked.

**Comment by freemangordon** [comment] 2024-05-08 17:36
> for the (low) standards of a desktop ui, a blur shader is a pretty expensive shader. what probubly happend here is that the new pvr ddk's shader compiler is doing a bit worse on this particular shader.

Right, but blur effect should be active only when transitioning launcher<->desktop, perhaps we hit some bug in h-d that makes blur active all the time

**Comment by MerlijnWajer** [comment] 2024-05-11 08:43
That is an interesting thought, about it being active all the time, but JFYI this isn't just launcher<->desktop, it is also for example power key menu, status menu, window expose, etc.

**Comment by Arno1103** [comment] 2024-05-11 17:36
BTW on boot, with all tweaks previously mentioned, the N900 is now immediately usable once the pin code has been entered, but i wonder why the PIN code applet is so slow to appear (almost 2-3 min).

I noticed that boot time is not so long now, that's Hildon-Desktop/Hildon-Home which takes a while to load (until the PIN code applet appears...)

**Comment by MerlijnWajer** [comment] 2024-08-25 17:59
Shall we close this issue?

**Closed by MerlijnWajer** 2024-08-25 17:59 UTC
