### ISSUE TITLE
Bugs in Maemo Leste images

### ISSUE THREAD

**Issue by spinal84** [maemo-leste/bugtracker#302] opened 2020-01-20 13:28 UTC
Here I propose to collect the bugs found in the latest Maemo Leste images available for download.

**Comment by spinal84** [comment] 2020-01-20 13:36
1. N900: led not responding on battery charge events. Fix: Settings -> Notification ligth -> Charging.
2. N900: ssh server installed refuses connections because of host keys errors. Fix: rm /etc/ssh/ssh_host_* && dpkg-reconfigure openssh-server
3. Droid4: A a very long delay for different commands ("sudo" for example) if there's no network connection. Fix: replace devuan with devuan-droid4 in /etc/hosts

**Comment by Suppresed** [comment] 2020-01-20 18:18
1. Droid 4: missing zram module.

**Comment by spinal84** [comment] 2020-01-20 20:40
> 1. Droid 4: missing zram module.
It seems more like a wish, not a bug. Please open separate ticket for this.

**Comment by MerlijnWajer** [comment] 2020-01-20 20:41
I asked him to report the bug here. We include a zram initscript by default, so I think it's expected to work, so probably fits the bug category?

**Comment by MerlijnWajer** [comment] 2020-01-20 20:41
By the way, regarding the ssh server host keys, I didn't have that problem. Maybe you interrupted the key generation process on first boot?

**Comment by spinal84** [comment] 2020-01-21 20:58
VirtualBox image seems to be useless.
Couldn't even launch xterm there.

**Comment by spinal84** [comment] 2020-01-22 00:23
> By the way, regarding the ssh server host keys, I didn't have that problem. Maybe you interrupted the key generation process on first boot?

I couldn't reproduce it the second time. It could be MicroSD I/O error. I'll cross out that bug report.

**Comment by spinal84** [comment] 2020-01-22 00:32
A lot of warning messages about duplicated entries in /etc/apt/sources.list and /etc/apt/sources.list.d/hildon-application-manager.list. The fix: remove duplicated repositories from /etc/apt/sources.list

**Comment by MerlijnWajer** [comment] 2020-01-24 18:47
About "apt update: a lot of warnings about duplicated entries in /etc/apt/sources.list and /etc/apt/sources.list.d/hildon-application-manager.list. The fix: remove duplicated repositories from /etc/apt/sources.list"

I think they might be copied initially from that file, or not? At least image builder uses them for sure.

**Comment by spinal84** [comment] 2020-01-24 19:55
I didn't dig in HAM yet, but isn't it possible to have only maemo-extras repo in its config for now?
Does it make sense to have all repos there?

**Comment by MerlijnWajer** [comment] 2020-01-26 16:57
It's possible, but I think it makes a lot more sense to have it all in there.

Allow people to enable -devel repo and such in the UI is a neat feature, and it works the same way on Maemo Fremantle, AFAIK. The Nokia repos are also in there.

**Comment by eloydegen** [comment] 2020-01-27 12:13
Bug: sometimes the Droid4 hangs, which is most probably caused by `musb` at hotplug events.

**Comment by MerlijnWajer** [comment] 2020-01-28 21:20
Another (important) point: disable sysrq. It causes random reboots.

**Comment by parazyd** [comment] 2020-01-30 11:58
@spinal84 Was 3. (the hostname issue) appearing also in the latest images? We do have a `sed` call that is supposed to replace it. Perhaps it's not working properly? https://github.com/maemo-leste/image-builder/blob/master/leste.blend#L36

**Comment by parazyd** [comment] 2020-01-30 11:59
> I didn't dig in HAM yet, but isn't it possible to have only maemo-extras repo in its config for now?
> Does it make sense to have all repos there?

HAM currently picks up anything it finds in /etc/apt/sources.list and sources.list.d, so it's something we'd have to rework in the code I believe.

**Comment by spinal84** [comment] 2020-01-30 16:33
> @spinal84 Was 3. (the hostname issue) appearing also in the latest images? We do have a `sed` call that is supposed to replace it. Perhaps it's not working properly? https://github.com/maemo-leste/image-builder/blob/master/leste.blend#L36

Everything written here is _only_ about the latest available images.
Please, read the first post in the thread.

**Comment by sicelo** [comment] 2020-01-31 20:28
> It's possible, but I think it makes a lot more sense to have it all in there.
> 
> Allow people to enable -devel repo and such in the UI is a neat feature, and it works the same way on Maemo Fremantle, AFAIK. The Nokia repos are also in there.

How about removing them from the `/etc/apt/sources.list` file, and keeping them in hildon-application-manager? that way, even apt can use them.
This is how it's setup in Fremantle - `/etc/apt/sources.list` is empty there. I tested this on my Leste devices and all works as expected, with no warnings.

**Comment by sicelo** [comment] 2020-02-05 11:01
DROID 4 - the backlight takes a very long time to turn off, much longer than what's in Settings > Display

**Comment by sicelo** [comment] 2020-02-15 15:39
> DROID 4 - the backlight takes a very long time to turn off, much longer than what's in Settings > Display
After some updates, this seems to be working as expected. Unfortunately I am not sure what exactly fixed it.

**Comment by MerlijnWajer** [comment] 2020-02-23 22:11
@spinal84 - we're planning to make some new images soon.

looks like we want the blacklist, the hostname fix (if not already), maybe the ham repo fix (duplicate) and the eth line for VM images.

cc @parazyd ^ ?

**Comment by parazyd** [comment] 2020-02-23 22:37
With Hildon Application Manager's catalogue, we can either change the code to work in a different way, or just have `-devel` and `extras` in the ham catalogue for now.

**Comment by clort81** [comment] 2020-02-25 07:30
root password is 'toor'.  

to press enter key on terminal hit left-shift + enter.

press keys slowly when entering password.

**Comment by spinal84** [comment] 2020-02-25 18:03
> Documentation: ( https://leste.maemo.org/Motorola_Droid_4 ) root password is 'toor'.
> Documentation: Installation: steps 3-4: enter fastboot (power+vol_down) _before_ connecting USB, not after.

The documentation you mentioned is a wiki page. Feel free to edit/improve it if you see issues there.
It's nothing to do with the images.

> * Droid4: to press enter key on terminal hit left-shift (mapped to ctrl) + enter.

This should be fixed after "apt update && apt upgrade" and rebooting the device.
The ticket is for the issues that can't be fixed with just "apt upgrade"

> * Droid4: press keys slowly when entering password.  Several missed keys on my device - hildon-tesktop taking 110-140% cpu.

How to fix this in the image?

> * Droid4: Any framebuffer fast-console available? X Terminal quite unresponsive.

Use xterm in fullscreen mode. Please ask such questions in IRC or open a separate issue. This one is for the images issues. So the developers can know what to fix when they prepare to release a new image.

> * Droid4: How do we enter ">" character?

Please use IRC channel or open a separate issue for such things.
The answer is press Caps Lock + . (point)

> * Droid4: Hildon Application Manager requests network connection despite USB0 interface up and apt working.

This should be fixed in the package, not in the image.
Please open a separate ticket for this issue.

> * Droid4: Battery indicator applet showing red 1-bar empty battery.  Killing HAM and letting it restart gave battery readout (animated, normal function).

Isn't this issue fixed with "apt update && apt upgrade" and rebooting the device?

> @parazyd "Was 3. (the hostname issue) appearing also in the latest images?" << issue did not appear for me - it is fine

There is a note: _"if there's no network connection"_.
Did you try to reproduce it without netwok available on Droid 4?

**Comment by spinal84** [comment] 2020-02-25 20:04
About removing maedevu.org entries from /etc/apt/sources.list file.
On N900 there's at least one component needed that's missing in /etc/apt/sources.list.d/* files: n900.
So, with these lines remaining in /etc/apt/sources.list it should be fine:
```
deb http://maedevu.maemo.org/leste ascii n900
deb http://maedevu.maemo.org/extras ascii n900
```
Or we need somehow to add such lines to HAM on per-device basis.

**Comment by parazyd** [comment] 2020-02-25 21:41
6. from https://github.com/maemo-leste/bugtracker/issues/302#issuecomment-576277674 is solved with this: https://github.com/maemo-leste/image-builder/commit/43882abb0edee6a1c9da6a55e045f47edba6cbce

**Comment by MerlijnWajer** [comment] 2020-03-02 12:19
Maybe we also want to mount debugfs from inittab?

https://github.com/maemo-leste/bugtracker/issues/317#issuecomment-591190206

**Comment by spinal84** [comment] 2020-03-02 12:22
> Maybe we also want to mount debugfs from inittab?
> [#317 (comment)](https://github.com/maemo-leste/bugtracker/issues/317#issuecomment-591190206)

No objections.

**Comment by MerlijnWajer** [comment] 2020-03-03 11:33
One other thing I'd like to vouch for, but not sure how other feels about it....

I usually have ssh started very early on in boot, and also have stuff like ke-recv and others started before X, or at least before Xsession, so that I can log into the device if there are any startup issues.

Wonder if we should do that in the images too.

**Comment by IMbackK** [comment] 2021-01-13 18:56
every thing here is fixed by now

**Closed** 2021-01-13 19:06 UTC
