### ISSUE TITLE
N900 20201227 image is not usable: black screen, buggy lock screen

### ISSUE THREAD

**Issue by ilya-bystrov** [maemo-leste/bugtracker#497] opened 2021-01-14 15:05 UTC
I've run maemo-leste-1.0-armhf-n900-20201227.img and found out that it's not usable.
Just black screen after boot logs.

After pressing power button multiple times I can get buggy lock with swipe. It fills only part of the device screen and swipe ball is in wrong place.

The similar behavior with maemo-leste-1.0-armhf-n900-20210110.img

Previously I've used maemo-leste-1.0-armhf-n900-20200323.img.xz and it worked fine.

**Comment by parazyd** [comment] 2021-01-14 17:51
I can't reproduce this with `maemo-leste-1.0-armhf-n900-20210110.img`

**Comment by MerlijnWajer** [comment] 2021-01-14 18:02
@ilya-bystrov  Does `maemo-leste-1.0-armhf-n900-20200323.img.xz` still boot normally for you, (albeit being old)?

**Comment by IMbackK** [comment] 2021-01-14 19:29
"After pressing power button multiple times I can get buggy lock with swipe. It fills only part of the device screen and swipe ball is in wrong place."
sounds kind of like the pvr problems mapphones have, the n900 might occasionally show this too, since its timing related. in gernally rendering while x is activating the display dosent work right. I think the n900 works because the device is slow but maybe its not that but rather the command mode display.

@ilya-bystrov could you post a picture of the display?

**Comment by IMbackK** [comment] 2021-01-14 19:29
id like to add that i cant reproduce this on n900 with my upgraded image.

**Comment by ilya-bystrov** [comment] 2021-01-15 00:41
> @ilya-bystrov could you post a picture of the display?
![image](https://user-images.githubusercontent.com/13896222/104665901-91e1ee80-56e3-11eb-8381-67265e94e898.png)

**Comment by ilya-bystrov** [comment] 2021-01-15 01:15
> @ilya-bystrov Does `maemo-leste-1.0-armhf-n900-20200323.img.xz` still boot normally for you, (albeit being old)?

Yeah, it works.

**Comment by ilya-bystrov** [comment] 2021-01-15 01:30
Hm, interesting, I've got another N900 device (but with scratches on the screen),
I put sdcard and battery in that device and it boots fine.

I remember that previously I also observed some differences in behavior, but I don't remember details (and it wasn't critical).

**Comment by ilya-bystrov** [comment] 2021-01-15 01:43
Here is picture of another (working) N900 device and the first one.

![image](https://user-images.githubusercontent.com/13896222/104669776-cc4f8980-56eb-11eb-955f-c7152f82b639.png)

Probably, different hardware versions?

**Comment by freemangordon** [comment] 2021-01-15 10:37
Do you have lockcode enabled on the non-working device?

**Comment by ilya-bystrov** [comment] 2021-01-15 13:08
> Do you have lockcode enabled on the non-working device?

Yes, it was enabled.

I'd disabled lockcode in Maemo 5 (boot from eMMC) and Maemo Leste was booted **successfully**.

Looks like that enabled lockcode leads to this issue.

Thanks!

**Comment by IMbackK** [comment] 2021-01-15 14:52
@ilya-bystrov in this case this is dupe of https://github.com/maemo-leste/bugtracker/issues/343 which has known cause and fix
thank you for reporting
please close

**Closed** 2021-01-15 15:47 UTC

**Comment by MerlijnWajer** [comment] 2021-01-17 00:35
For the record bug #495 is now fixed, and will make it to the main repos in a matter of days, and then you should be able to boot with lock code.
