### ISSUE TITLE
Add sub menu for all debian packages to /etc/xdg/menus/hildon.menu

### ISSUE THREAD

**Issue by MerlijnWajer** [maemo-leste/bugtracker#360] opened 2020-04-13 10:16 UTC
We should be able to add a sub menu that contains all the debian entries, but not the hildon ones.

**Comment by MerlijnWajer** [comment] 2020-04-13 10:16
Also see https://specifications.freedesktop.org/menu-spec/menu-spec-1.0.html

And maybe the catorise source can help http://maemo.org/downloads/product/Maemo5/catorise/

**Comment by MerlijnWajer** [comment] 2020-04-13 10:19
https://wiki.maemo.org/Application_Menu#Catorise_Plus.2F_Catorise_.2F_Catorise_GUI

**Comment by MerlijnWajer** [comment] 2020-04-13 19:15
So adding this as a submenu does something:

```
  <Menu>
    <Name>Debian</Name>
    <Directory>debian.directory</Directory>

    <AppDir>/usr/share/applications</AppDir>
    <DirectoryDir>/usr/share/applications</DirectoryDir>

    <LegacyDir>/usr/share/applications/hildon</LegacyDir>

    <Include>
        <All/>
    </Include>
  </Menu>
```

Also needs this:

```
# cat /usr/share/applications/hildon/debian.directory
[Desktop Entry]
Type=Directory
Name=Debian
```

Then you will get a sub menu with all the apps, but also the hildon ones (some of them double?), but it's a start.

**Comment by dderby** [comment] 2020-04-13 20:28
This is possibly a duplicate of #82.  I would be happy with your proposed solution of using a submenu.

**Comment by MerlijnWajer** [comment] 2020-04-13 21:55
It's not perfect yet -- there are duplicate entries, and the hildon ones are there too, so we might want to do something on insertion of new .desktop files, there are probably dpkg hooks for that.

@parazyd ?

**Comment by MerlijnWajer** [comment] 2020-04-13 21:55
I also think the `LegacyDir` has no effect.

**Comment by MerlijnWajer** [comment] 2020-04-13 21:56
And yes, you're right, it is a duplicate.

**Comment by MerlijnWajer** [comment] 2020-06-08 23:09
Just for reference, I don't have it working yet, but this is what I had working on April 13.

![image](https://user-images.githubusercontent.com/517897/84088843-cd019e00-a9ed-11ea-9942-547e786e21d8.png)
![image](https://user-images.githubusercontent.com/517897/84088845-cffc8e80-a9ed-11ea-8791-a9812fe2477e.png)

**Comment by parazyd** [comment] 2020-07-05 20:51
Implemented in https://github.com/maemo-leste/hildon-desktop/commit/604d1167860d5750fffe097de121bd7a3e2885f7

**Closed by parazyd** 2020-07-05 20:51 UTC
