### ISSUE TITLE
N900: Provide images for bigger SD card

### ISSUE THREAD

**Issue by pavelmachek** [maemo-leste/bugtracker#59] opened 2018-02-06 12:29 UTC
Would it be possible to provide images for bigger SD card? If I attempt to install pretty basic tools ("ofono emacs git mplayer gcc"), I run out of disk space :-(.

**Comment by parazyd** [comment] 2018-02-06 12:41
It's not exactly convenient because the `dd` process would take *much* longer.

You are rather supposed to resize the second (root) partition yourself using `resize2fs`.

**Comment by MerlijnWajer** [comment] 2018-02-06 13:37
On Linux you can do a live resize (of mounted /):

1. fdisk /dev/mmcblk0
2. Delete partition 2 and re-add it on the same block
3. partprobe /dev/mmcblk0
4. resize2fs /dev/mmcblk0

**Comment by MerlijnWajer** [comment] 2018-02-06 13:38
We could provide a script for this, perhaps.

**Comment by pkillnine** [comment] 2018-02-06 15:21
heh I got into the same problem, I used gparted to expand the SD card partition to fill the whole available space

**Comment by ollieparanoid** [comment] 2018-02-06 19:25
(postmarketOS does this in the [initramfs](https://github.com/postmarketOS/pmbootstrap/blob/d0acbca4f2ab37eb19135ce5edb707310760a7b1/aports/main/postmarketos-mkinitfs/init_functions.sh#L132-L160) on first boot)

**Comment by parazyd** [comment] 2018-02-06 20:12
We hope to avoid using ramdisks/initramfs while allowed. ext4 can be
resized live, while mounted RW as well, so having a script in place
should not cause any problems.

**Comment by dderby** [comment] 2018-02-19 22:39
The problem with providing images is that everyone has different requirements.  I didn't get on with the pre-built images because I already have multiple slices on my SD card and I needed an image with a single file system rather than two slices with a separate `/boot`.

Tarballs are available as an alternative to images.  I'd recommend anyone with custom requirements to just slice their SD card or eMMC as they desire and then unpack the tarball.

**Comment by MerlijnWajer** [comment] 2018-02-19 22:41
What about providing a script for the four steps I listed? Running that could then be optional. But yeah, people might as well just run that themselves...

**Comment by parazyd** [comment] 2018-02-24 14:22
I have a script that will work with ext4. I'll include it in future builds.

**Comment by MerlijnWajer** [comment] 2018-02-25 23:47
Cool. When you do, let's close the bug report.

**Comment by enyc00000000** [comment] 2018-03-08 18:47
An important usage-case to take account of in your scripts, is that of dual-boot with existing maemo, and being able to update/replace leste image without constantly taking fragile microsd-card in/out....  Useful for 'testers', regression-analysis, and so-forth.

I like the idea of being able to mount/access/fix leste-image on an SD-card-PARTITION, from existing cssu, which is fine with power kernel / tools, if only your ext4 images were formatted  "-O ^64bit,^metadata_csum"  ... we really don't need support for > 16tb sd-cards you-know!, and its' caused issues with ubuntu-16.04 LTS systems even.

Scripts should 'take this into account' bearing in mind the mke2fs on maemo-cssu will NOT support/accept those parameters, whereas on ascii you need those flags to turn off enabled-by-default incompatible feature...  Checking for 'mke2fs -V' >= 1.43 should suffice I think...

Do think on the 'transitionary arrangements' and 'convenience for testers including installing-updates and recovering broken leste'...  Setup a wiki so I can help fix documentation on installation-scripts/examples?

**Comment by MerlijnWajer** [comment] 2018-06-19 15:07
@parazyd did you ever include this script?

**Comment by MerlijnWajer** [comment] 2018-08-31 20:55
There is a script in place in the latest images, but it doesn't seem to work properly/at-all yet.

**Comment by sicelo** [comment] 2018-09-03 01:45
Couple of issues:

1. The script has some bashisms: `[[ "$UID" = 0 ]]` does not work in /bin/sh - perhaps we should use `[[  $(id -u) = 0 ]]` instead
2. The execute bit should be set in the file's permissions

(and more ... but will finish it up tomorrow)

**Comment by parazyd** [comment] 2018-09-03 14:38
Closing. We merged @sicelo 's patch. Thanks!

**Closed by parazyd** 2018-09-03 14:38 UTC
Labels: Distribution
