### ISSUE TITLE
Droid 4 High Power Usage (linux 5.7.0, 5.8.0)

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#452] opened 2020-09-13 20:40 UTC
Seeing **189-292 mA** at 4.09V, idle CPU, with latest image installed on a fresh microSD card (wlan on, nothing showing in 'top', backlight 4/5 bars)

Started with: 303188660 Sep 12 08:11  maemo-leste-1.0-armhf-droid4-20200906.img.xz

Upgraded linux-image to Linux devuan-droid4 5.7.0 #1 SMP PREEMPT Mon Jul 27 19:03:46 UTC 2020 armv7l GNU/Linux

No system tweaks made.

Powertop (after calibration) reports 1.58W, 1.3W, 1.18W, 1.4W, 1,32W 
CPU Use reported by powertop is usually around 125%, up to 400% while top reports 0-2%

Various runs of powertop usually show delayed_work_timer_fn and other things using > 300ms/s
```
PowerTOP 2.8      Overview   Idle stats   Frequency stats   Device stats   Tunables   

The battery reports a discharge rate of 1.34 W

Summary: 46.4 wakeups/second,  0.0 GPU ops/seconds, 0.0 VFS ops/sec and 257.1% CPU use

                Usage       Events/s    Category       Description
            838.5 ms/s       3.7        Timer          hrtimer_wakeup
            558.0 ms/s      0.00        Timer          delayed_work_timer_fn
            223.4 ms/s      0.00        Timer          fib6_gc_timer_cb
            192.5 ms/s       0.8        kWork          gc_worker
            152.4 ms/s      11.4        kWork          dbs_work_handler
            176.9 ms/s      0.00        Interrupt      [16] gp_time
```

After another few updates,
```
PowerTOP 2.8      Overview   Idle stats   Frequency stats   Device stats   Tunables   

The battery reports a discharge rate of 1.18 W

Summary: 35.8 wakeups/second,  0.0 GPU ops/seconds, 0.0 VFS ops/sec and 283.1% CPU use

                Usage       Events/s    Category       Description
            444.0 ms/s      0.00        Timer          delayed_work_timer_fn
            411.7 ms/s      0.10        Timer          it_real_fn
            352.3 ms/s       5.0        kWork          dbs_work_handler
            324.7 ms/s       1.0        Timer          pm_suspend_timer_fn
            193.9 ms/s      0.00        Timer          blk_rq_timed_out_timer
            148.6 ms/s       8.6        Timer          tick_sched_timer
            156.9 ms/s      0.00        Interrupt      [16] gp_timer
            156.0 ms/s      0.00        Timer          process_timeout
            153.3 ms/s      0.25        Timer          hrtimer_wakeup
```

The Idle stats look more sensible:
```
          Package   |            CPU 0
C1          0.5%    | C1          0.6%    0.5 ms
C2          0.0%    | C2          0.0%    1.4 ms
C3         98.8% 
```

Device stats are a bit odd perhaps?
```
The battery reports a discharge rate of 1.40 W

              Usage     Device name
            203.5%        CPU use
              0.0%        Display backlight
              0.0 pkts/s  nic:usb0
            100.0%        USB device: Flash MZ600 (Motorola, Incorporated)
            100.0%        USB device: Generic Platform OHCI controller
              0.3 pkts/s  Network interface: wlan0 (wl12xx_driver)
              0.0%        USB device: MUSB HDRC host driver
```
* Is anyone else seeing abnormally high power drain in the wlan-on, no sim, no bluetooth, idle state?  
* Can I share more info to identify the problem?
* How can I get back to the 70-80mA range of idle drain?

[EDIT] found droid4-powermanagement stuff 
# To check no device drivers or busy timers are blocking SoC idle states,
# check that the RET count keeps increasing when doing:
#

```
grep ^core_pwrdm /sys/kernel/debug/pm_debug/count
core_pwrdm (ON),OFF:0,RET:0,INA:0,ON:1,RET-LOGIC-OFF:0,RET-MEMBANK1-OFF:0,RET-MEMBANK2-OFF:0,RET-MEMBANK3-OFF:0,RET-MEMBANK4-OFF:0,RET-MEMBANK5-OFF:0
core_pwrdm (ON),OFF:0,RET:0,INA:0,ON:1,RET-LOGIC-OFF:0,RET-MEMBANK1-OFF:0,RET-MEMBANK2-OFF:0,RET-MEMBANK3-OFF:0,RET-MEMBANK4-OFF:0,RET-MEMBANK5-OFF:0
core_pwrdm (ON),OFF:0,RET:0,INA:0,ON:1,RET-LOGIC-OFF:0,RET-MEMBANK1-OFF:0,RET-MEMBANK2-OFF:0,RET-MEMBANK3-OFF:0,RET-MEMBANK4-OFF:0,RET-MEMBANK5-OFF:0
core_pwrdm (ON),OFF:0,RET:0,INA:0,ON:1,RET-LOGIC-OFF:0,RET-MEMBANK1-OFF:0,RET-MEMBANK2-OFF:0,RET-MEMBANK3-OFF:0,RET-MEMBANK4-OFF:0,RET-MEMBANK5-OFF:0
core_pwrdm (ON),OFF:0,RET:0,INA:0,ON:1,RET-LOGIC-OFF:0,RET-MEMBANK1-OFF:0,RET-MEMBANK2-OFF:0,RET-MEMBANK3-OFF:0,RET-MEMBANK4-OFF:0,RET-MEMBANK5-OFF:0
```
/etc/init.d/droid4-powermanagement status returns  
```
root@devuan-droid4:~# /etc/init.d/droid4-powermanagement status
d=2020-09-14|t=00:16:02|i=OFF:0,RET:0|p=650|c=NA|b=none
root@devuan-droid4:~# vi /etc/crontab 
root@devuan-droid4:~# /etc/init.d/droid4-powermanagement status
d=2020-09-14|t=00:16:24|i=OFF:0,RET:0|p=877|c=NA|b=none
root@devuan-droid4:~# /etc/init.d/droid4-powermanagement status
d=2020-09-14|t=00:16:38|i=OFF:0,RET:0|p=622|c=NA|b=none
root@devuan-droid4:~# /etc/init.d/droid4-powermanagement status
d=2020-09-14|t=00:16:44|i=OFF:0,RET:0|p=724|c=NA|b=none
root@devuan-droid4:~# /etc/init.d/droid4-powermanagement status
d=2020-09-14|t=00:16:49|i=OFF:0,RET:0|p=732|c=NA|b=none
```

**Comment by clort81** [comment] 2020-09-17 15:12
On 5.8.0 with a fresh boot, brightness 4/5 inside, i get current_avg 
181097
262905
221328
213884
216971
209286
with a fresh charge @ 4.11v

What are you guys seeing?
top showing mce @ 1.3% cpu

**Comment by IMbackK** [comment] 2020-09-22 11:43
yeah this is bugged. this often happens to me too, its related to the motmdm usb device not ideling. you can "fix" this by blacklisting phy_mapphone_mdm6600, but then you have no audio, no gnss and no modem. 

normaly it spontaniously resolves after a couple of days. i think somehow the modem gets into a funny state. inserting a sim dosent help, and the modem otherwise works fine in the broken idle state

**Comment by clort81** [comment] 2020-09-23 21:39
> phy_mapphone_mdm6600

Thank you!  blacklisting this (and bluetooth and sound) gets me backlight-off, wlan-on idle current of 38mA @ 3.8V.   That's about 35.6 hours of idle with my 1352mAH battery.

Powertop now reports 65-74 wakeups/second. 

On my device modem kernel wakeups problem hasn't 'solved itself' after several weeks, so I will experiment disconnecting battery.

**Comment by IMbackK** [comment] 2020-09-24 08:44
@clort81 please unblacklist all modules you blacklisted, and tell me what `cat /sys/bus/usb/devices/2-1/power/control` returns.

**Comment by clort81** [comment] 2020-09-26 02:56
Currently blacklisted:
blacklist ehci-omap
blacklist hci-uart
blacklist omap_hdq
blacklist bluetooth

cat /sys/bus/usb/devices/2-1/power/control
on
Gets ~186mA drain, screen on, wlan on.

> /etc/udev/rules.d/55-modem.rules
Does **not** exist

Un-blacklisting everything gets around 320mA drain and wifi no longer works
and cat /sys/bus/usb/devices/2-1/power/control is not present.

**Comment by clort81** [comment] 2020-10-08 04:40
Starting from around 750mW use, wifi on, screen off
rmmod -f phy-mapphone-mdm6600 
gets me into 211-280 mW range: wifi on, screen off

I notice audio still works with killed phy-mapphone-mdm6600.

Tony on lkml reports:
```
idle lcd off	phy-mapphone-mdm6600    ohci-platform
153mW		284mW	                                344mW
```


I'd like to be able

**Comment by IMbackK** [comment] 2020-10-08 13:11
this problem has been fixed in latest -devel

**Comment by clort81** [comment] 2020-10-08 22:19
Hi IMbackK, thanks for your work!  I saw https://github.com/IMbackK/droid4-pm/commit/5b1878ff9685c70c40092da736704fddc81d3c88  

FTR: Screen backlight off, wlan on now gets me average 266mW 
 ```
root@ml2:~# /etc/init.d/droid4-powermanagement status
d=2020-10-08|t=22:09:54|i=OFF:0,RET:0|p=268|c=NA|b=none
d=2020-10-08|t=22:10:37|i=OFF:0,RET:0|p=245|c=NA|b=none
d=2020-10-08|t=22:11:35|i=OFF:0,RET:0|p=287|c=NA|b=none
d=2020-10-08|t=22:12:59|i=OFF:0,RET:0|p=251|c=NA|b=none
d=2020-10-08|t=22:15:09|i=OFF:0,RET:0|p=276|c=NA|b=none
```
which is much better.  it's possible the bad wlan here causes some higher power drain than others are seeing.

After your changes, rmmod phy-mapphone-mdm6600 yields no improvement.

Cheers!

**Comment by IMbackK** [comment] 2020-10-09 09:58
if you have no sim in the device you should also CFUN=0 the modem via `printf 'U1234AT+CFUN=0\r' > /dev/gsmtty1` then you after letting the device idle for a while `/etc/init.d/droid4-powermanagement status` should report RET > 0. power should then be at about ~80mW maybe slightly above ~120mW (caused by another known bug)

**Comment by IMbackK** [comment] 2020-10-09 09:58
@MerlijnWajer close this pls

**Closed** 2020-10-09 10:09 UTC

**Comment by clort81** [comment] 2020-10-09 12:35
Hello, I have updated leste -devel on three devices and monitored idle, screen off, wlan on power at 2 minute intervals with 
/etc/init.d/droid4-powermanagement status  
```
æ1 /root# ./powerstat.sh
d=2020-10-09|t=11:52:07|i=OFF:0,RET:6502|p=228|c=NA|b=none
d=2020-10-09|t=11:54:07|i=OFF:0,RET:6738|p=153|c=NA|b=none
d=2020-10-09|t=11:56:07|i=OFF:0,RET:6960|p=124|c=NA|b=none
d=2020-10-09|t=11:58:08|i=OFF:0,RET:7202|p=171|c=NA|b=none
d=2020-10-09|t=12:00:08|i=OFF:0,RET:7466|p=133|c=NA|b=none
d=2020-10-09|t=12:02:08|i=OFF:0,RET:7694|p=176|c=NA|b=none
d=2020-10-09|t=12:04:08|i=OFF:0,RET:7950|p=126|c=NA|b=none

æ2 /root# ./powerstat.sh
d=2020-10-09|t=11:52:02|i=OFF:0,RET:2480|p=261|c=NA|b=none
d=2020-10-09|t=11:54:03|i=OFF:0,RET:2718|p=143|c=NA|b=none
d=2020-10-09|t=11:56:03|i=OFF:0,RET:2986|p=134|c=NA|b=none
d=2020-10-09|t=11:58:03|i=OFF:0,RET:3222|p=163|c=NA|b=none
d=2020-10-09|t=12:00:03|i=OFF:0,RET:3440|p=151|c=NA|b=none
d=2020-10-09|t=12:02:03|i=OFF:0,RET:3710|p=150|c=NA|b=none
d=2020-10-09|t=12:04:03|i=OFF:0,RET:3948|p=150|c=NA|b=none

æ3 /root# ./powerstat.sh
d=2020-10-09|t=12:21:24|i=OFF:0,RET:806|p=178|c=NA|b=none
d=2020-10-09|t=12:23:24|i=OFF:0,RET:1096|p=153|c=NA|b=none
d=2020-10-09|t=12:25:25|i=OFF:0,RET:1332|p=128|c=NA|b=none
d=2020-10-09|t=12:27:25|i=OFF:0,RET:1578|p=126|c=NA|b=none
d=2020-10-09|t=12:29:25|i=OFF:0,RET:1830|p=127|c=NA|b=none
d=2020-10-09|t=12:31:25|i=OFF:0,RET:2096|p=124|c=NA|b=none
d=2020-10-09|t=12:33:25|i=OFF:0,RET:2342|p=140|c=NA|b=none
```
