### ISSUE TITLE
Phone makes continuous noises when operated on usb power.

### ISSUE THREAD

**Issue by clort81** [maemo-leste/bugtracker#512] opened 2021-04-19 13:12 UTC
I make here a feature request to disable the constant notifications and noises when operating on USB power.

**Comment by IMbackK** [comment] 2021-04-19 13:25
@clort81 please refrain from repeated duplicate feature requests this is a dupe of https://github.com/maemo-leste/bugtracker/issues/511
@MerlijnWajer recommend close

**Closed** 2021-04-19 14:22 UTC
