### ISSUE TITLE
Input focus on Qt5 applications does not work

### ISSUE THREAD

**Issue by IMbackK** [maemo-leste/bugtracker#346] opened 2020-03-28 12:42 UTC
On the 2020-03-23 image, both updated via apt and not the telegram-desktop window never gets input focus. when the window is selected some other window retains keyboard focus.

EDIT: this appears to affect all qt5 programs

**Comment by MerlijnWajer** [comment] 2020-03-28 21:27
Thanks for the report. I'm going to work Qt5 in the next one or two weeks, so this will likely get picked up too, then. It's probably related to hildon-input-method support.

**Comment by MerlijnWajer** [comment] 2020-04-01 16:37
So this is related: https://github.com/maemo-leste/bugtracker/issues/53

**Comment by MerlijnWajer** [comment] 2020-04-05 22:13
So I've taken a closer look with meridion, and it looks like X is not assigning keyboard focus to Qt5.

I've verified this with a custom C program:

```
root@devuan:~# ./xfocus
Window ID: 18874383
ret: 1
name: xterm
```

Doing the same for my sample Countdown timer application:

```
root@devuan:~# ./xfocus
Window ID: 12582922
ret: 1
name: desktop
```

```
# cat xfocus.c
#include <X11/Xlib.h>
#include <stdio.h>

int main() {

        Display* dis = XOpenDisplay(NULL);
        int ret;
        Window window;

        XGetInputFocus(dis, &window, &ret);
        fprintf(stderr, "Window ID: %d\n", window);
        fprintf(stderr, "ret: %d\n", ret);

        char * name = NULL;
        XFetchName(dis, window, &name);
```


Killing `hildon-desktop` and starting matchbox instead makes it work. So there's either some patch Qt is missing, or some misbehaviour by Qt/hildon-desktop/matchbox.

We'll get there...

cc @freemangordon

**Comment by MerlijnWajer** [comment] 2020-04-05 22:20
Looking with `xprop` to see all that is different... Maybe comparing with Fremantle will be helpful too.

Gravity is `Static` for Qt, and `NorthWest` for gtk2.

**Comment by MerlijnWajer** [comment] 2020-04-05 22:34
OK, I *think* figured it out.

Compare:

Maemo qt 4: https://github.com/community-ssu/qt-x11-maemo/blob/master/src/gui/kernel/qwidget_x11.cpp#L1973

Upstream qt5 w/ xcb: https://github.com/qt/qtbase/blob/dev/src/plugins/platforms/xcb/qxcbwindow.cpp#L1448

Looks like Maemo qt4 unconditionally calls `XSetInputFocus` anyway.

Maybe h-d is unhappy with this atom being used to activate/raise.

89ae85094f2c88e77c941c8c106f8cd18cf973ff (old qt4) seems relevant, but doesn't contain much info

**Comment by MerlijnWajer** [comment] 2020-04-06 18:27
Just as an update, my above hunch was correct.

I made a one line change to the xcb platform plugin (don't do that, will fix it proper in maemo5 platform as fork of xcb plugin):

```
diff --git a/src/plugins/platforms/xcb/qxcbwindow.cpp b/src/plugins/platforms/xcb/qxcbwindow.cpp
index 59b06d543e..2239e736be 100644
--- a/src/plugins/platforms/xcb/qxcbwindow.cpp
+++ b/src/plugins/platforms/xcb/qxcbwindow.cpp
@@ -1635,9 +1635,8 @@ void QXcbWindow::requestActivateWindow()
         xcb_send_event(xcb_connection(), 0, xcbScreen()->root(),
                        XCB_EVENT_MASK_STRUCTURE_NOTIFY | XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT,
                        (const char *)&event);
-    } else {
-        xcb_set_input_focus(xcb_connection(), XCB_INPUT_FOCUS_PARENT, m_window, connection()->time());
     }
+    xcb_set_input_focus(xcb_connection(), XCB_INPUT_FOCUS_PARENT, m_window, connection()->time());

     connection()->sync();
 }
```

**Comment by IMbackK** [comment] 2020-04-06 21:23
why is this nessecary? how dose the maemo wm behave differently to a normal wm? should we not fix its behaviour instead of basically implementing focus stealing?

**Comment by MerlijnWajer** [comment] 2020-04-06 21:29
Good questions.

It works OK in matchbox, but not in hildon-desktop. They use the same base, so perhaps hildon-desktop is doing something weird and it has to be fixed.

However, what I am trying to do is port Qt4 from Maemo5 era to Qt5 for Maemo Leste.

If that means I have to initially carry this one line change, I think I will do it, and look at if/how we can fix hildon-desktop (if this is indeed somehow not by design) later on.

It's kind of a "pick your battles" for me atm. Once Qt5 works wonderfully, we can see what can be done about this. Of course, don't let me stop you from doing this, I just don't have the time and the know-how.

**Comment by MerlijnWajer** [comment] 2020-04-06 21:32
The "fix" that I show above is not exactly focus stealing, it is working around a problem that causes the window manager *not* to give focus when it should. I think that should be fixed, too. And it was originally present in maemo5 qt4 as well, so Nokia engineers must have decided it was either a hard thing to fix, or perhaps by design. Or they lacked manpower. :)

**Comment by MerlijnWajer** [comment] 2020-04-07 07:45
Also found this text:

```
#ifdef Q_WS_MAEMO_5
                // according to the ICCCM, the XSetInputFocus() should be optional for non-modal windows
                // see also <http://mail.gnome.org/archives/wm-spec-list/2007-March/msg00001.html>
                // seems like the Maemo5 WM is broken in that regard and always needs an explicit
                // XSetInputFocus() call with the time parameter set to the WM_TAKE_FOCUS message's time.
                else if (w) {
                    XSetInputFocus(X11->display, w->internalWinId(), XRevertToParent, event->xclient.data.l[1]);
                }
#endif
```

in `src/gui/kernel/qapplication_x11.cpp`

**Comment by freemangordon** [comment] 2020-04-07 08:16
Maybe this is the same problem tmlind sees in es2gears not receiving keyboard events

**Comment by IMbackK** [comment] 2020-04-07 08:50
ill look into it

**Closed** 2020-04-15 15:20 UTC
