### ISSUE TITLE
N900 Battery never reaches "fully charged" state

### ISSUE THREAD

**Issue by druk13** [maemo-leste/bugtracker#167] opened 2018-08-17 07:25 UTC
I've installed and updated maeme-leste. But after starting leste, periodically the message "Battery low" pops up. Also the battery indicator seems to be broken. How can I fix it?

**Comment by sicelo** [comment] 2018-08-17 07:48
You have to calibrate the battery meter by charging the device to full (preferably with a wall charger), and then allow it to discharge completely (till it powers off). While discharging, do not connect the device to the computer via USB, as that will start charging it, and resetting the discharge flag in the battery meter.

**Comment by druk13** [comment] 2018-08-17 10:41
Thank's sicelo, do I understand it right:
If the battery is calibrated and working without problems with maema-fremantle, I've had to load the battery until it's full under maemo-leste and then run the phone till it shuts down?

**Comment by sicelo** [comment] 2018-08-17 20:12
Yes. Because stock Maemo sometimes shuts down the device too early, before the battery meter has reached its threshold, I would recommend you don't use Maemo Fremantle for this. Just charge in Maemo Leste, and also discharge in Leste

**Comment by druk13** [comment] 2018-08-20 08:27
I've loaded the battery in maemo leste and recognized, that the loading of the battery will not stop automatically when 100 % or with my battery 1398 mAh is reached. Could this behavior be a bug?

**Comment by MerlijnWajer** [comment] 2018-08-20 08:36
The battery low issues are caused by a non calibrated battery. If you no longer get that, then your battery is fixed. The other issue, that it doesn't show the 'full' icon but rather shows the charging animation, is ultimately a problem in UPower and I have not hacked around it yet. (Or fixed it properly)

**Comment by MerlijnWajer** [comment] 2018-12-08 17:00
I think that this PR fixes most of these issues https://github.com/maemo-leste/status-area-applet-battery/pull/2 

It is now available in leste-devel if you want to try it, and I think it will end up in the normal repo in a few days.

**Comment by spinal84** [comment] 2018-12-22 01:10
MerlijnWajer moved updated packages to the stable repository. The issue should be fixed now.
Please check.

**Comment by MerlijnWajer** [comment] 2018-12-22 15:07
I can confirm it reaches full battery state; as the mce patterns show a green led. Thanks!

**Comment by sicelo** [comment] 2024-03-01 08:47
This problem resurfaced for some reason...

Anyway, what promises to be permanent fix is merging, in the specified order, the following:

https://github.com/maemo-leste/droid4-linux/pull/8
https://github.com/maemo-leste/mce/pull/59  (DONE)
https://github.com/maemo-leste/mce/pull/60
https://github.com/maemo-leste/status-area-applet-battery/pull/7

**Comment by sicelo** [comment] 2024-07-08 09:22
all patches were merged, so issue can be closed

**Closed by sicelo** 2024-07-08 09:22 UTC
