### ISSUE TITLE
Remove Nokia brandings 

### ISSUE THREAD

**Issue by ZhanYF** [maemo-leste/bugtracker#733] opened 2024-04-26 01:08 UTC
Try to install anything in App. Manager will result in a warning about application not provided by Nokia.

E-Mail client also warns about Nokia's privacy policy and data collection.

**Comment by IMbackK** [comment] 2024-04-26 11:04
dupe of https://github.com/maemo-leste/bugtracker/issues/311

**Closed by IMbackK** 2024-04-26 11:04 UTC
